name: C++ CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y g++-11 cmake libgtest-dev
          sudo update-alternatives --set g++ /usr/bin/g++-11
          # 手动编译GTest（解决系统源版本问题）
          cd /usr/src/gtest
          sudo cmake . -DCMAKE_CXX_STANDARD=17
          sudo make
          sudo cp lib/*.a /usr/lib/
      - name: Compile & Test
        run: |
          # 明确指定C++17标准（核心！）
          g++ -std=c++17 main.cpp test.cpp -o test -lgtest -lgtest_main -pthread
          ./test